language: smalltalk
sudo: false

os:
  - linux

env:
  global:
    - EXCLUDE_CATEGORIES="Cryptography,PostgresV2"

smalltalk:
  - Squeak-5.1
  - Squeak-5.0

addons:
  apt:
    packages:
    # UUIDPlugin
    - libuuid1:i386
  postgresql: "9.5"

before_install:
  - psql -c "CREATE DATABASE squeakdb;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'bird';" -U postgres
